# fly.toml app configuration file generated for myphonebookproject on 2023-07-03T11:36:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "myphonebookproject"
primary_region = "jnb"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[env]
  PORT = "3000"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
